#!/bin/zsh

# brew
/bin/bash -c \
  "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install \
  neovim-nightly \
  pandoc \
  python3
brew tap \
  homebrew/cask-fonts \
  jason0x43/homebrew-neovim-nightly
brew install --cask \
  iterm2 \
  font-fira-code \
  qutebrowser \
  r

# pip
pip3 install -U \
  radian \
  pygments \
  pygments-solarized

# configs
cp -r .config ~/.config
cp .zshrc ~/.zshrc
nvim +PlugInstall +qall

# defaults
defaults write -g InitialKeyRepeat -int 10
defaults write -g KeyRepeat -int 1

# end
reboot
