#!/bin/bash

# brew
/bin/bash -c \
  "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install \
  neovim-nightly \
  python3
brew tap \
  homebrew/cask-fonts \
  jason0x43/homebrew-neovim-nightly
brew install --cask \
  iterm2 \
  font-fira-code \
  qutebrowser \
  r

# pip
pip3 install -U \
  radian \
  pygments \
  pygments-solarized

# neovim
mkdir ~/.config/nvim
cp nvim ~/.config
nvim +PlugInstall +qall

# radian
mkdir ~/.config/radian
cp -r radian ~/.config
python3 radian/vimpyg.py radian/seoul256.vim > seoul256.py
mv seoul256.py /usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pygments/styles/seoul256.py

# config
defaults write -g InitialKeyRepeat -int 10
defaults write -g KeyRepeat -int 1

# end
reboot
