#!/bin/zsh

# brew
/bin/bash -c \
  "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install \
    fd \
    neovim-nightly \
    pandoc \
    python3
brew tap \
    homebrew/cask-fonts \
    jason0x43/homebrew-neovim-nightly
brew install --cask \
    iterm2 \
    font-fira-code \
    julia \
    qutebrowser \
    r

# configs
# mkdir ~/.config
ln -s $PWD/.zshrc ~/.zshrc
ln -s $PWD/.config ~/.config
nvim  +PlugInstall +qall
nvim +CocInstall coc-julia coc-r +qall

# defaults
defaults write -g InitialKeyRepeat -int 10
defaults write -g KeyRepeat -int 1

# pip
pip3 install -U \
  nord-pygments \
  radian

reboot
