#!/bin/bash

brew install neovim
mkdir ~/.config/nvim
cp nvim/init.vim ~/.config/nvim/init.vim
nvim +PlugInstall +qall

brew tap homebrew/cask-fonts
brew install --cask \
  iterm2 \
  font-fira-code \
  font-fira-mono \
  font-fira-sans

